### ISSUE TITLE
[ FEATURE ] Docker

### ISSUE THREAD

**Issue by doob187** [saltydk/SARotate#4]
FEATURE Requests

I know sarotate is not designed to run inside a Docker, but would it be possible to make this Docker based?

King Regards

**Comment by saltydk** [comment]
In its current state it requires to be installed alongside rclone since it does not currently remote control through http so you would have to deploy it with rclone to get it to work in a container. How that fits your use case would be up to you.

Rewriting sarotate to use http requests instead isn't really in the current plans since it was mostly built for how Cloudbox/Saltbox uses rclone but I suppose it could happen at a later date. The rclone rc commands themselves can traverse docker networks just fine regardless so I see no reason why you couldn't get it working as is.

I could look at supporting a container if such a rewrite were to happen but I cannot say when or even if that will happen.

**Comment by saltydk** [comment]
Rewrite was done and a proof of concept dockerfile exists in the repo. I do not plan on testing it any time soon though so your mileage may vary.
